#!/bin/bash
# displaz user information from the system

echo "USer info for userid: $USER"
echo UID: $UID
echo HOME: $HOME

denis    tty2         2023-03-12 12:04 (tty2)
denis    pts/2        2023-03-12 12:14
